# Example of host monitoring configuration

hostMonitoring:
  enabled: true
  hosts:
  - name: host-01
    description: Host 01 Node Exporter
    jobName: host-01
    host:
      address: 1.2.3.3
    serviceMonitor:
      endpoints:
      - port: "9100"  # Node exporter port
        interval: 30s
        path: /metrics
  - name: host-02
    description: Host 02 Node Exporter
    jobName: host-02
    host:
      address: 1.2.3.4
    serviceMonitor:
      endpoints:
      - port: "9100"
        interval: 30s
        path: /metrics
    apps:
    - name: host-02-docker
      description: Host 02 Docker Containers
      jobName: host-02-docker
      templates:
        cAdvisor:
          enable: true
      serviceMonitor:
        endpoints:
        - port: "9101"
          interval: 30s
          path: /metrics

templates:
  L1:
    host:
      # Override warning thresholds for node disk panel and alert
      overallUtilizationDisk:
        panel:
          thresholds:
            warning: 50
        alert:
          thresholds:
            warning: 50
