# Helper values file for dnation-kubernetes-monitoring local dev deployment

dnation-kubernetes-monitoring:
  enabled: false

kube-prometheus-stack:
  kubeEtcd:
    service:
      port: 2381
      targetPort: 2381
  prometheus:
    service:
      type: NodePort
      nodePort: 30090
  grafana:
    service:
      type: NodePort
      nodePort: 30001
  alertmanager:
    service:
      type: NodePort
      nodePort: 30903
