{{- if and .Values.hostMonitoring.enabled }}
  {{ $host_service_monitors := dict }}
  {{- range .Values.hostMonitoring.hosts }}
    {{ if hasKey . "serviceMonitor" }}
      {{ $name := (printf "%s-%s-%s" (include "k8s-monitoring.fullname" $) .name .jobName | lower | trunc 63 | trimSuffix "-") }}
      {{ $_ := set .serviceMonitor "jobName" .jobName }}
      {{ $_ := set $host_service_monitors $name .serviceMonitor }}
    {{- end }}
    {{ if hasKey . "apps" }}
      {{- range .apps }}
        {{ $name := (printf "%s-%s-%s" (include "k8s-monitoring.fullname" $) .name .jobName | lower | trunc 63 | trimSuffix "-") }}
        {{ $_ := set .serviceMonitor "jobName" .jobName }}
        {{ $_ := set $host_service_monitors $name .serviceMonitor }}
      {{- end }}
    {{- end }}
  {{- end }}

{{- if $host_service_monitors }}
apiVersion: v1
kind: List
items:
{{- range $name, $serviceMonitor := $host_service_monitors }}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    namespace: {{ include "k8s-monitoring.namespace" $ }}
    name: {{ $name }}
    labels:
{{ include "k8s-monitoring.labels" $ | indent 6 }}
      app: {{ include "k8s-monitoring.name" $ }}
      release: {{ include "k8s-monitoring.release" $ }}
  spec:
    endpoints:
{{ toYaml $serviceMonitor.endpoints | indent 4 }}
    jobLabel: {{ $serviceMonitor.jobLabel | default "host/app" }}
    namespaceSelector:
  {{- if $serviceMonitor.namespaceSelector }}
{{ toYaml $serviceMonitor.namespaceSelector | indent 6 }}
  {{- else }}
      matchNames:
      - {{ include "k8s-monitoring.namespace" $ }}
  {{- end }}
    selector:
  {{- if $serviceMonitor.selector }}
{{ toYaml $serviceMonitor.selector | indent 6 }}
  {{- else }}
      matchLabels:
        {{ $serviceMonitor.jobLabel | default "host/app" }}: {{ $serviceMonitor.jobName }}
  {{- end }}
  {{- if $serviceMonitor.targetLabels }}
    targetLabels:
{{ toYaml $serviceMonitor.targetLabels | indent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
