#
# Copyright 2020 The dNation Kubernetes Monitoring Authors. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if and .Values.hostMonitoring.enabled }}
  {{ $host_service_monitors := dict }}
  {{- range .Values.hostMonitoring.hosts }}
    {{ $address := .host.address }}
    {{ if hasKey . "serviceMonitor" }}
      {{ $name := (printf "%s-%s-%s" (include "k8s-monitoring.fullname" $) .name .jobName | lower | trunc 63 | trimSuffix "-") }}
      {{ $_ := set .serviceMonitor "address" $address }}
      {{ $_ := set .serviceMonitor "jobName" .jobName }}
      {{ $_ := set $host_service_monitors $name .serviceMonitor }}
    {{- end }}
    {{ if hasKey . "apps" }}
      {{- range .apps }}
        {{ $name := (printf "%s-%s-%s" (include "k8s-monitoring.fullname" $) .name .jobName | lower | trunc 63 | trimSuffix "-") }}
        {{ $_ := set .serviceMonitor "address" $address }}
        {{ $_ := set .serviceMonitor "jobName" .jobName }}
        {{ $_ := set $host_service_monitors $name .serviceMonitor }}
      {{- end }}
    {{- end }}
  {{- end }}

{{- if $host_service_monitors }}
apiVersion: v1
kind: List
items:
{{- range $name, $serviceMonitor := $host_service_monitors }}
- apiVersion: v1
  kind: Service
  metadata:
    namespace: {{ include "k8s-monitoring.namespace" $ }}
    name: {{ $name }}
    labels:
{{ include "k8s-monitoring.labels" $ | indent 6 }}
      app: {{ include "k8s-monitoring.name" $ }}
      release: {{ $.Release.Name }}
      {{ $serviceMonitor.jobLabel | default "host/app" }}: {{ $serviceMonitor.jobName }}
  spec:
    type: ExternalName
    externalName: {{ $serviceMonitor.address }}
    ports:
    - name: {{ (first $serviceMonitor.endpoints).port | quote }}
      port: {{ (first $serviceMonitor.endpoints).port }}
{{- end }}
{{- end }}
{{- end }}
