#
# Copyright 2020 The dNation Kubernetes Monitoring Authors. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if and .Values.clusterMonitoring.enabled }}
  {{ $vm_service_monitors := dict }}
  {{- range .Values.clusterMonitoring.clusters }}
    {{ if hasKey . "vms" }}
      {{- range .vms }}
        {{ if hasKey . "serviceMonitor" }}
          {{ $name := (printf "%s-%s-%s" (include "k8s-monitoring.fullname" $) .name .jobName | lower | trunc 63 | trimSuffix "-") }}
          {{ $_ := set $vm_service_monitors $name .serviceMonitor }}
        {{- end }}
        {{ if hasKey . "apps" }}
          {{- range .apps }}
            {{ if hasKey . "serviceMonitor" }}
              {{ $name := (printf "%s-%s-%s" (include "k8s-monitoring.fullname" $) .name .jobName | lower | trunc 63 | trimSuffix "-") }}
              {{ $_ := set $vm_service_monitors $name .serviceMonitor }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}

{{- if $vm_service_monitors }}
apiVersion: v1
kind: List
items:
{{- range $name, $serviceMonitor := $vm_service_monitors }}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    namespace: {{ include "k8s-monitoring.namespace" $ }}
    name: {{ $name }}
    labels:
{{ include "k8s-monitoring.labels" $ | indent 6 }}
      app: {{ include "k8s-monitoring.name" $ }}
      release: {{ include "k8s-monitoring.release" $ }}
  spec:
    endpoints:
{{ toYaml $serviceMonitor.endpoints | indent 4 }}
  {{- if $serviceMonitor.jobLabel }}
    jobLabel: {{ $serviceMonitor.jobLabel }}
  {{- end }}
  {{- if $serviceMonitor.namespaceSelector }}
    namespaceSelector:
{{ toYaml $serviceMonitor.namespaceSelector | indent 6 }}
  {{- end }}
    selector:
{{ toYaml $serviceMonitor.selector | indent 6 }}
  {{- if $serviceMonitor.targetLabels }}
    targetLabels:
{{ toYaml $serviceMonitor.targetLabels | indent 6 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
