variables:
  # When using DinD service, we need to instruct docker, to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default /var/run/docker.sock socket.
  DOCKER_HOST: "tcp://docker:2375"

.base-helm:
  image: dtzar/helm-kubectl:3.3.1
  before_script:
  - apk add --update make
  tags:
  - docker
  - privileged
  only:
  - merge_requests
  - main

.base-jsonnet:
  image: docker:18.09
  before_script:
  - apk add --update make
  tags:
  - docker
  - privileged
  only:
  - merge_requests
  - main
  services:
  - docker:18.09-dind

stages:
- package jsonnet
- build helm
- test
- publish

package jsonnet:
  stage: package jsonnet
  extends: .base-jsonnet
  script:
  - make jsonnet-package
  artifacts:
    paths:
    - chart/jsonnet-*tar.gz

build helm package:
  stage: build helm
  extends: .base-helm
  script:
  - helm package -u -d chart/release chart
  artifacts:
    paths:
    - chart/release/

test lint:
  stage: test
  extends: .base-helm
  script:
  - make helm-lint

test lint jsonnet:
  stage: test
  extends: .base-jsonnet
  script:
  - make jsonnet-lint

test build jsonnet:
  stage: test
  extends: .base-jsonnet
  script:
  - make json-dashboards
  - make json-rules

publish:
  stage: publish
  image: cfmanteiga/alpine-bash-curl-jq
  only:
  - main
  script:
  - curl --fail --user "$IFNE_HELM_USER":"$IFNE_HELM_PASS" "$IFNE_HELM_URL" --upload-file chart/release/dnation-kubernetes-monitoring-*.tgz
  when: manual
