{
 "title": "Apache",
 "tags": [
  "k8s",
  "app",
  "L1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(apache__c_p_u_load{cluster=~\"$cluster\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apache Requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apache__req_per_sec{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apache CPU Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(apache__c_p_u_load{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
       "legendFormat": "load"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apache Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(apache__total_k_bytes_total{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Apache Memory Utilization per Sec/Req",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(apache__bytes_per_sec{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
       "legendFormat": "bytes per sec"
      },
      {
       "expr": "rate(apache__bytes_per_req{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
       "legendFormat": "bytes per req"
      }
     ]
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Apache Workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apache__idle_workers{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "idle"
    },
    {
     "expr": "rate(apache__busy_workers{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "busy"
    }
   ]
  }
 ]
}