{
 "title": "Api Server",
 "tags": [
  "k8s",
  "system",
  "L2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(apiserver_request_total, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(apiserver_request_total{cluster=~\"$cluster\", job=\"apiserver\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Availability (30d) > 99.000%",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{cluster=~\"$cluster\", verb=\"all\"}"
    }
   ]
  },
  {
   "title": "ErrorBudget (30d) > 99.000%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "100 * (apiserver_request:availability30d{cluster=~\"$cluster\", verb=\"all\"} - 0.990000)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  {
   "title": "Read Availability (30d)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{cluster=~\"$cluster\", verb=\"read\"}"
    }
   ]
  },
  {
   "title": "Read SLI - Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(code_resource:apiserver_request_total:rate5m{cluster=~\"$cluster\", verb=\"read\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Read SLI - Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (code_resource:apiserver_request_total:rate5m{cluster=~\"$cluster\", verb=\"read\", code=~\"5..\"}) / sum by (resource) (code_resource:apiserver_request_total:rate5m{cluster=~\"$cluster\", verb=\"read\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Read SLI - Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{cluster=~\"$cluster\", verb=\"read\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Write Availability (30d)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{cluster=~\"$cluster\", verb=\"write\"}"
    }
   ]
  },
  {
   "title": "Write SLI - Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(code_resource:apiserver_request_total:rate5m{cluster=~\"$cluster\", verb=\"write\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Write SLI - Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (code_resource:apiserver_request_total:rate5m{cluster=~\"$cluster\", verb=\"write\", code=~\"5..\"}) / sum by (resource) (code_resource:apiserver_request_total:rate5m{cluster=~\"$cluster\", verb=\"write\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Write SLI - Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{cluster=~\"$cluster\", verb=\"write\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{cluster=~\"$cluster|\", job=\"apiserver\"}) / count(up{cluster=~\"$cluster|\", job=\"apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "GRPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\", code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\", code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\", code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\", code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\", verb!=\"WATCH\"}[5m])) by (verb, le))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{cluster=~\"$cluster\", job=\"apiserver\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}