{
 "title": "CAdvisor",
 "tags": [
  "k8s",
  "app",
  "L1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(container_cpu_user_seconds_total{cluster=~\"$cluster\"}, job)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_cpu_user_seconds_total{cluster=~\"$cluster\", job=~\"$job\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m]))"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_cpu_user_seconds_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}) by (name,image)"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Disk Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m])) by (name)",
       "legendFormat": "read {{name}}"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m])) by (name)",
       "legendFormat": "written {{name}}"
      },
      {
       "expr": "sum(rate(container_fs_io_time_seconds_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m])) by (name)",
       "legendFormat": "io time {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwith",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m])",
       "legendFormat": "Tx_{{name}}"
      },
      {
       "expr": "irate(container_network_receive_bytes_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m])",
       "legendFormat": "Rx_{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Drops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m])",
       "legendFormat": "Tx_{{name}}"
      },
      {
       "expr": "irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m])",
       "legendFormat": "Rx_{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(container_network_transmit_errors_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m])",
       "legendFormat": "Tx_{{name}}"
      },
      {
       "expr": "irate(container_network_receive_errors_total{cluster=~\"$cluster\", job=~\"$job\", image!=\"\", name=~\"$container\"}[5m])",
       "legendFormat": "Rx_{{name}}"
      }
     ]
    }
   ]
  }
 ]
}