{
 "title": "CPU per Node",
 "tags": [
  "k8s",
  "overview",
  "L2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Nodes",
    "query": "label_values(node_uname_info{cluster=~\"$cluster\", job=~\"$job\"}, nodename)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_exporter_build_info{cluster=~\"$cluster\", pod!~\"\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU per Node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round((1 - (avg by (instance) (irate(node_cpu_seconds_total{cluster=~\"$cluster\", job=~\"$job\", mode=\"idle\"}[5m])))) * 100)\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "round((1 - (avg(irate(node_cpu_seconds_total{cluster=~\"$cluster\", job=~\"$job\", mode=\"idle\"}[5m])\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}))) * 100)",
       "legendFormat": "cpu usage"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{cluster=~\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "1m load average"
      },
      {
       "expr": "node_load5{cluster=~\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "5m load average"
      },
      {
       "expr": "node_load15{cluster=~\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "15m load average"
      },
      {
       "expr": "count(node_cpu_seconds_total{cluster=~\"$cluster\", job=~\"$job\", mode=\"idle\"}\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"})",
       "legendFormat": "logical cores"
      }
     ]
    }
   ]
  }
 ]
}