{
 "title": "Disk per Node",
 "tags": [
  "k8s",
  "overview",
  "L2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Nodes",
    "query": "label_values(node_uname_info{cluster=~\"$cluster\", job=~\"$job\"}, nodename)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_exporter_build_info{cluster=~\"$cluster\", pod!~\"\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk per Node",
   "type": "grafana-polystat-panel",
   "description": "The percentage of the disk utilization is calculated using the fraction:\n```\n<space used>/(<space used> + <space free>)\n```\nThe value of <space free> is reduced by  5% of the available disk capacity, because   \nthe file system marks 5% of the available disk capacity as reserved. \nIf less than 5% is free, using the remaining reserved space requires root privileges.\nAny non-privileged users and processes are unable to write new data to the partition. See the list of explicitly ignored mount points and file systems [here](https://github.com/dNationCloud/kubernetes-monitoring-stack/blob/main/chart/values.yaml)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(round(\n(sum(node_filesystem_size_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (instance, device) - sum(node_filesystem_free_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (instance, device)) /\n(sum(node_filesystem_size_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (instance, device) - sum(node_filesystem_free_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (instance, device) +\nsum(node_filesystem_avail_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (instance, device))\n * 100\n) * on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}) by (nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization",
     "type": "graph",
     "description": "The percentage of the disk utilization is calculated using the fraction:\n```\n<space used>/(<space used> + <space free>)\n```\nThe value of <space free> is reduced by  5% of the available disk capacity, because   \nthe file system marks 5% of the available disk capacity as reserved. \nIf less than 5% is free, using the remaining reserved space requires root privileges.\nAny non-privileged users and processes are unable to write new data to the partition\n.\n                       See the list of explicitly ignored mount points and file systems [here](https://github.com/dNationCloud/kubernetes-monitoring-stack/blob/main/chart/values.yaml)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(sum(node_filesystem_size_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (device, instance) - sum(node_filesystem_free_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (device, instance))\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "disk used {{device}}"
      },
      {
       "expr": "sum(node_filesystem_size_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (device, instance)\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "disk size {{device}}"
      },
      {
       "expr": "sum(node_filesystem_avail_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (device, instance)\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "disk available {{device}}"
      },
      {
       "expr": "round((sum(node_filesystem_size_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (device, instance, nodename) - sum(node_filesystem_free_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (device, instance, nodename)) / (sum(node_filesystem_size_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (device, instance, nodename) - sum(node_filesystem_free_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (device, instance, nodename) + sum(node_filesystem_avail_bytes{cluster=~\"$cluster\", job=~\"$job\"}) by (device, instance, nodename)) * 100 * on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"})",
       "legendFormat": "disk utilization {{device}}"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{cluster=~\"$cluster\", job=~\"$job\"}[5m])) by (instance)\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "read {{device}}"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{cluster=~\"$cluster\", job=~\"$job\"}[5m])) by (instance)\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "written {{device}}"
      },
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{cluster=~\"$cluster\", job=~\"$job\"}[5m])) by (instance)\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "io time {{device}}"
      }
     ]
    }
   ]
  }
 ]
}