{
 "title": "Etcd",
 "tags": [
  "k8s",
  "system",
  "L2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(etcd_server_has_leader{cluster=~\"$cluster\", job=\"kube-etcd\"}, instance)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(etcd_server_has_leader, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{cluster=~\"$cluster|\", job=\"kube-etcd\"}) / count(up{cluster=~\"$cluster|\", job=\"kube-etcd\"})) * 100"
    }
   ]
  },
  {
   "title": "GRPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\", grpc_type=\"unary\"}[5m]))",
     "legendFormat": "GRPC_Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\", grpc_type=\"unary\", grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "GRPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Watch\", grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Watch\", grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Lease\", grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Lease\", grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Resident Memory"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Total Leader Elections PerDay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"}[1d])",
     "legendFormat": "Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "Raft Proposal",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"})",
     "legendFormat": "etcd_server_proposals_pending"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{cluster=~\"$cluster\", job=\"kube-etcd\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  }
 ]
}