{
 "title": "Java Actuator",
 "tags": [
  "k8s",
  "app",
  "L1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "datasource_logs", "label": "Logs datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(jvm_memory_used_bytes{cluster=~\"$cluster\"}, job)"
   },
   { "name": "view", "label": "View by", "query": "pod,container" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\"}, container)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", area=\"nonheap\"},id)"
   },
   { "name": "search", "label": "Logs Search" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}) by ($view)",
       "legendFormat": "{{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_requests_cpu_cores{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodRequests - {{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_limits_cpu_cores{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodLimits - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", id!=\"\", container!=\"POD\", container=~\"$container\"}) by ($view)",
       "legendFormat": "{{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodRequests - {{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodLimits - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Tx_{{pod}}"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Rx_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "HTTP"
      }
     ]
    },
    {
     "title": "Success Rate (non-4|5xx responses)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", status=~\"[4-5].*\"}[1m]))",
       "legendFormat": "HTTP - 5xx|4xx"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", status!~\"5..\"}[1m]))",
       "legendFormat": "HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", status!~\"5..\"})",
       "legendFormat": "HTTP - MAX"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Drops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Tx_{{pod}}"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Rx_{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", area=\"heap\"}) by ($view)",
     "legendFormat": "used - {{$view}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", area=\"heap\"}) by ($view)",
     "legendFormat": "committed - {{$view}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", area=\"heap\"}) by ($view)",
     "legendFormat": "max - {{$view}}"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", area=\"nonheap\"}) by ($view)",
     "legendFormat": "used - {{$view}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", area=\"nonheap\"}) by ($view)",
     "legendFormat": "committed - {{$view}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", area=\"nonheap\"}) by ($view)",
     "legendFormat": "max - {{$view}}"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "used - {{$view}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "committed - {{$view}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "max - {{$view}}"
    },
    {
     "expr": "sum(process_memory_vss_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "vss - {{$view}}"
    },
    {
     "expr": "sum(process_memory_rss_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "rss - {{$view}}"
    },
    {
     "expr": "sum(process_memory_pss_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "pss - {{$view}}"
    },
    {
     "expr": "sum(process_memory_swap_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "swap - {{$view}}"
    },
    {
     "expr": "sum(process_memory_swappss_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "swappss - {{$view}}"
    },
    {
     "expr": "sum(process_memory_pss_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view) + sum(process_memory_swap_bytes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "phys (pss+swap) - {{$view}}"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_live{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view) or sum(jvm_threads_live_threads{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view) ",
       "legendFormat": "live - {{$view}}"
      },
      {
       "expr": "sum(jvm_threads_daemon{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})  by ($view)  or sum(jvm_threads_daemon_threads{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
       "legendFormat": "daemon - {{$view}}"
      },
      {
       "expr": "sum(jvm_threads_peak{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})  by ($view)  or sum(jvm_threads_peak_threads{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
       "legendFormat": "peak - {{$view}}"
      },
      {
       "expr": "sum(process_threads{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})  by ($view)",
       "legendFormat": "process - {{$view}}"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_states_threads{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})  by (state, $view)",
       "legendFormat": "{{state}} - {{$view}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_open_fds{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
       "legendFormat": "open - {{$view}}"
      },
      {
       "expr": "sum(process_max_fds{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
       "legendFormat": "max - {{$view}}"
      },
      {
       "expr": "sum(process_files_open{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view) or sum(process_files_open_files{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
       "legendFormat": "open - {{$view}}"
      },
      {
       "expr": "sum(process_files_max{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view) or sum(process_files_max_files{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
       "legendFormat": "max - {{$view}}"
      }
     ]
    },
    {
     "title": "Log Events (1m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])) by (level, $view)",
       "legendFormat": "{{level}} - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools(Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"$jvm_memory_pool_heap\"}) by ($view)",
       "legendFormat": "used - {{$view}}"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"$jvm_memory_pool_heap\"}) by ($view)",
       "legendFormat": "commited - {{$view}}"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"$jvm_memory_pool_heap\"}) by ($view)",
       "legendFormat": "max - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools(Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"${jvm_memory_pool_nonheap:raw}\"}) by ($view)",
       "legendFormat": "used - {{$view}}"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"${jvm_memory_pool_nonheap:raw}\"}) by ($view)",
       "legendFormat": "commited - {{$view}}"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"${jvm_memory_pool_nonheap:raw}\"}) by ($view)",
       "legendFormat": "max - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_count{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])) by (action, cause, $view)",
       "legendFormat": "{{action}} ({{cause}}) - {{$view}}"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])) by (action, cause, $view) /sum(rate(jvm_gc_pause_seconds_count{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])) by (action, cause, $view)",
       "legendFormat": "avg {{action}} ({{cause}}) - {{$view}}"
      },
      {
       "expr": "sum(jvm_gc_pause_seconds_max{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (action, cause, $view)",
       "legendFormat": "max {{action}} ({{cause}}) - {{$view}}"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_memory_allocated_bytes_total{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])) by ($view)",
       "legendFormat": "allocated - {{$view}}"
      },
      {
       "expr": "sum(rate(jvm_gc_memory_promoted_bytes_total{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])) by ($view)",
       "legendFormat": "promoted - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_classes_loaded{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view) or sum(jvm_classes_loaded_classes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
       "legendFormat": "loaded - {{$view}}"
      }
     ]
    },
    {
     "title": "Class delta (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(jvm_classes_loaded{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m])) by ($view) or sum(delta(jvm_classes_loaded_classes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m])) by ($view)",
       "legendFormat": "delta - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers (Memory Used Bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"direct\"}) by ($view)",
       "legendFormat": "used - {{$view}}"
      },
      {
       "expr": "sum(jvm_buffer_total_capacity_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"direct\"}) by ($view)",
       "legendFormat": "capacity - {{$view}}"
      }
     ]
    },
    {
     "title": "Direct Buffers (Count)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_buffer_count{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"direct\"}) by ($view) or sum(jvm_buffer_count_buffers{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"direct\"}) by ($view)",
       "legendFormat": "count - {{$view}}"
      }
     ]
    },
    {
     "title": "Mapped Buffers (Memory Used Bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"mapped\"}) by ($view)",
       "legendFormat": "used - {{$view}}"
      },
      {
       "expr": "sum(jvm_buffer_total_capacity_bytes{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"mapped\"}) by ($view)",
       "legendFormat": "capacity - {{$view}}"
      }
     ]
    },
    {
     "title": "Mapped Buffers (Count)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_buffer_count{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"mapped\"}) by ($view) or sum(jvm_buffer_count_buffers{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", id=\"mapped\"}) by ($view)",
       "legendFormat": "count - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count (avg for 10s intervals)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "logs" }
     ],
     "targets": [
      {
       "expr": "sum(count_over_time({cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"(?i)$search\"[10s])) by ($view)",
       "legendFormat": "{{$view}}"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"(?i)$search\""
      }
     ]
    }
   ]
  }
 ]
}