{
 "title": "Network per Node",
 "tags": [
  "k8s",
  "overview",
  "L2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Nodes",
    "query": "label_values(node_uname_info{cluster=~\"$cluster\", job=~\"$job\"}, nodename)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_exporter_build_info{cluster=~\"$cluster\", pod!~\"\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Errors per Node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(rate(node_network_transmit_errs_total{cluster=~\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m]))  by (instance) \n   + sum(rate(node_network_receive_errs_total{cluster=~\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m])) by (instance))\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_errs_total{cluster=~\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m])\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "Tx_{{device}}"
      },
      {
       "expr": "rate(node_network_receive_errs_total{cluster=~\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m])\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "Rx_{{device}}"
      }
     ]
    },
    {
     "title": "Network Received",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{cluster=~\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m])\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m])\n* on(instance) group_left(nodename) \n   node_uname_info{cluster=~\"$cluster\", nodename=~\"$instance\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  }
 ]
}