{
 "title": "Nginx Ingress",
 "tags": [
  "k8s",
  "app",
  "L1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "datasource_logs", "label": "Logs datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\"}, job)"
   },
   { "name": "view", "label": "View by", "query": "pod,container" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\", job=~\"$job\"}, controller_namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\"}, container)"
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": "label_values(nginx_ingress_controller_requests{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}, ingress)"
   },
   { "name": "search", "label": "Logs Search" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}) by ($view)",
       "legendFormat": "{{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_requests_cpu_cores{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodRequests - {{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_limits_cpu_cores{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodLimits - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", id!=\"\", container!=\"POD\", container=~\"$container\"}) by ($view)",
       "legendFormat": "{{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodRequests - {{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodLimits - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Tx_{{pod}}"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Rx_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Drops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Tx_{{pod}}"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Rx_{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Ingress overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Controller Request Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{cluster=~\"$cluster\", job=~\"$job\", controller_pod=~\"$pod\", namespace=~\"$namespace\", container=~\"$container\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_success{cluster=~\"$cluster\", job=~\"$job\", controller_pod=~\"$pod\", controller_namespace=~\"$namespace\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{cluster=~\"$cluster\", job=~\"$job\", controller_pod=~\"$pod\", controller_namespace=~\"$namespace\", ingress=~\"$ingress\", container=~\"$container\"}[5m])) by (ingress), 0.001)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{cluster=~\"$cluster\", job=~\"$job\", controller_pod=~\"$pod\", controller_namespace=~\"$namespace\", container=~\"$container\"}[5m]))"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful{cluster=~\"$cluster\", job=~\"$job\", controller_pod=~\"$pod\",controller_namespace=~\"$namespace\", container=~\"$container\"} == 0)"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\", job=~\"$job\", controller_pod=~\"$pod\",namespace=~\"$namespace\",status!~\"[4-5].*\", container=~\"$container\"}[5m])) / sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\", job=~\"$job\", controller_pod=~\"$pod\", namespace=~\"$namespace\", container=~\"$container\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\", job=~\"$job\", controller_pod=~\"$pod\",namespace=~\"$namespace\",ingress=~\"$ingress\",status!~\"[4-5].*\",  container=~\"$container\"}[5m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\", job=~\"$job\", controller_pod=~\"$pod\",namespace=~\"$namespace\",  container=~\"$container\", ingress=~\"$ingress\"}[5m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingress Percentile Response Times and Transfer Rates",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"$job\", ingress!=\"\", controller_pod=~\"$pod\",  container=~\"$container\", controller_namespace=~\"$namespace\", ingress=~\"$ingress\"}[5m])) by (le, ingress))"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"$job\", ingress!=\"\", controller_pod=~\"$pod\",  container=~\"$container\", controller_namespace=~\"$namespace\", ingress=~\"$ingress\"}[5m])) by (le, ingress))"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"$job\", ingress!=\"\", controller_pod=~\"$pod\",  container=~\"$container\", controller_namespace=~\"$namespace\", ingress=~\"$ingress\"}[5m])) by (le, ingress))"
      },
      {
       "expr": "sum(irate(nginx_ingress_controller_request_size_sum{cluster=~\"$cluster\", job=~\"$job\", ingress!=\"\", controller_pod=~\"$pod\",  container=~\"$container\", controller_namespace=~\"$namespace\", ingress=~\"$ingress\"}[5m])) by (ingress)"
      },
      {
       "expr": "sum(irate(nginx_ingress_controller_response_size_sum{cluster=~\"$cluster\", job=~\"$job\", ingress!=\"\", controller_pod=~\"$pod\",  container=~\"$container\", controller_namespace=~\"$namespace\", ingress=~\"$ingress\"}[5m])) by (ingress)"
      }
     ]
    }
   ]
  },
  { "title": "Ingress Certificate Expiry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Ingress Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{cluster=~\"$cluster\", job=~\"$job\", pod=~\"$pod\", namespace=~\"$namespace\", container=~\"$container\"}) by (host) - time()"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count (avg for 10s intervals)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "logs" }
     ],
     "targets": [
      {
       "expr": "sum(count_over_time({cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"(?i)$search\"[10s])) by ($view)",
       "legendFormat": "{{$view}}"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"(?i)$search\""
      }
     ]
    }
   ]
  }
 ]
}