{
 "title": "PHP FPM",
 "tags": [
  "k8s",
  "app",
  "L1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(fpm_accepted_conn_total{cluster=~\"$cluster\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PHP FPM accepted connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fpm_accepted_conn_total{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "PHP FPM slow requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fpm_slow_requests_total{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
       "legendFormat": "requests"
      }
     ]
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PHP FPM processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fpm_max_active_processes{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "max active processes"
    },
    {
     "expr": "rate(fpm_active_processes{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "active processes"
    },
    {
     "expr": "rate(fpm_total_processes{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "total processes"
    },
    {
     "expr": "rate(fpm_idle_processes{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "idle processes"
    }
   ]
  },
  {
   "title": "PHP FPM max children processes reached",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fpm_max_children_reached{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "children processes"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "PHP FPM listen queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fpm_max_listen_queue{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "max listen queue"
    },
    {
     "expr": "rate(fpm_listen_queue{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "listen queue"
    },
    {
     "expr": "rate(fpm_listen_queue_len{cluster=~\"$cluster\", job=~\"$job\"}[5m])",
     "legendFormat": "listen queue len"
    }
   ]
  }
 ]
}