{
 "title": "Python Flask",
 "tags": [
  "k8s",
  "app",
  "L1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "datasource_logs", "label": "Logs datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(flask_exporter_info{cluster=~\"$cluster\"}, job)"
   },
   { "name": "view", "label": "View by", "query": "pod,container" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(flask_exporter_info{cluster=~\"$cluster\", job=~\"$job\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(flask_exporter_info{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(flask_exporter_info{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\"}, container)"
   },
   { "name": "search", "label": "Logs Search" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}) by ($view)",
       "legendFormat": "{{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_requests_cpu_cores{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodRequests - {{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_limits_cpu_cores{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodLimits - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", id!=\"\", container!=\"POD\", container=~\"$container\"}) by ($view)",
       "legendFormat": "{{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodRequests - {{$view}}"
      },
      {
       "expr": "sum(\nkube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)\n",
       "legendFormat": "PodLimits - {{$view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Tx_{{pod}}"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Rx_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Drops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Tx_{{pod}}"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Rx_{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(\n  flask_http_request_total{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m]\n) / 2) by (status, $view)",
     "legendFormat": "HTTP {{status}} - {{$view}}"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    flask_http_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", status!=\"200\"}[1m]\n)\n) by (status, $view)",
     "legendFormat": "HTTP {{status}} - {{$view}}"
    }
   ]
  },
  {
   "title": "Average response time [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(\n  flask_http_request_duration_seconds_sum{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", status=\"200\"}[1m]\n)\n /\nrate(\n  flask_http_request_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", status=\"200\"}[1m]\n) >= 0)  by (status, $view)",
     "legendFormat": "HTTP 200 - {{$view}}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(\n  flask_http_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", status=\"200\",le=\"0.25\"}[1m]\n)\n / ignoring (le)\nincrease(\n  flask_http_request_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", status=\"200\"}[1m]\n) >= 0) by (status, $view)",
     "legendFormat": "HTTP 200 - {{$view}}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "description": "The 50th percentile of request durations over the last 60 seconds. In other words, half of the requests finish in (min/max/avg) these times.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(\n  0.5,\n  rate(\n    flask_http_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", status=\"200\"}[1m]\n  )\n)>=0) by (status, $view)",
     "legendFormat": "HTTP 200 - {{$view}}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "description": "The 90th percentile of request durations over the last 60 seconds. In other words, 90 percent of the requests finish in (min/max/avg) these times.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(\n  0.9,\n  rate(\n    flask_http_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", status=\"200\"}[1m]\n  )\n)>=0) by (status, $view)",
     "legendFormat": "HTTP 200 - {{$view}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count (avg for 10s intervals)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "logs" }
     ],
     "targets": [
      {
       "expr": "sum(count_over_time({cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"(?i)$search\"[10s])) by ($view)",
       "legendFormat": "{{$view}}"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"(?i)$search\""
      }
     ]
    }
   ]
  }
 ]
}