{
 "title": "StatefulSet Detail",
 "tags": [
  "k8s",
  "statefulset",
  "L3"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_statefulset_metadata_generation, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_statefulset_metadata_generation{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "statefulset",
    "label": "StatefulSet",
    "query": "label_values(kube_statefulset_metadata_generation{cluster=~\"$cluster\", namespace=~\"$namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$statefulset.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$statefulset.*\", container!~\"POD|\", id!=\"\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$statefulset.*\"}[5m])) + sum(rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$statefulset.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas{cluster=~\"$cluster\", namespace=~\"$namespace\", statefulset=~\"$statefulset\"})"
    }
   ]
  },
  {
   "title": "Replicas of current version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_current{cluster=~\"$cluster\", namespace=~\"$namespace\", statefulset=~\"$statefulset\"})"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_observed_generation{cluster=~\"$cluster\", namespace=~\"$namespace\", statefulset=~\"$statefulset\"})"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_metadata_generation{statefulset=~\"$statefulset\", cluster=~\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_statefulset_replicas{statefulset=~\"$statefulset\", cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (statefulset)",
     "legendFormat": "replicas specified {{statefulset}}"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas{statefulset=~\"$statefulset\", cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (statefulset)",
     "legendFormat": "replicas created {{statefulset}}"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{statefulset=~\"$statefulset\", cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (statefulset)",
     "legendFormat": "ready {{statefulset}}"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas_current{statefulset=~\"$statefulset\", cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (statefulset)",
     "legendFormat": "replicas of current version {{statefulset}}"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas_updated{statefulset=~\"$statefulset\", cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (statefulset)",
     "legendFormat": "updated {{statefulset}}"
    }
   ]
  }
 ]
}