name: Lint and Test Chart

on:
  pull_request:
    # Only if there are chart changes to test.
    paths:
    - 'chart/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Run chart-testing (lint)
      uses: helm/chart-testing-action@v1.0.0
      with:
        command: lint
        config: .github/ct.yaml

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
        - v1.17.5
        - v1.19.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Create kind ${{ matrix.k8s }} cluster
      uses: helm/kind-action@v1.0.0
      with:
        node_image: kindest/node:${{ matrix.k8s }}

    - name: Run chart-testing (install)
      uses: helm/chart-testing-action@v1.0.0
      with:
        command: install
        config: .github/ct.yaml
